In [3]:
import tensorflow as tf

#create variable
w = tf.Variable([[0.5,1.0]])
x = tf.Variable([[2.0],[1.0]])
y = tf.matmul(w,x)#矩阵乘法

#init all the variable
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(y.eval())#输出y的值使用的方法



[[ 2.]]


In [ ]:
#常用变量定义方法
tf.zeros([3,4],int32)  #[[0,0,0,0],[0,0,0,0],[0,0,0,0]]

a = tf.Variable([[1,2,3,],[4,5,6]])
tf.zeros_like(a)  #[[0,0,0],[0,0,0]]
tf.ones([2,3],int32) #[[1,1,1],[1,1,1]]

tf.ones_like(a) #[[1,1,1],[1,1,1]]
tf.constant([0,1,2,3,4,5,6,7,8,9])  #[0,1,2,3,4,5,6,7,8,9]
tf.constant(-1.0,shape=[2,3])  #[[-1,-1,-1],[-1,-1,-1]]

tf.linspace(10.0,12.0,3,name="linspace") #[10.0,11.0,12.0]

tf.range(3,18,3)  #start=3,limit=18,delta=3 -->[3,6,9,12,15]

In [5]:
norm = tf.random_normal([2,3],mean = -1,stddev = 4) #mean 为均值，stddev为方差
c = tf.constant([[1,2],[3,4],[5,6]])
shuff = tf.random_shuffle(c)#洗牌操作

sess = tf.Session()
print(sess.run(norm))
print(sess.run(shuff))

[[-0.14204991 -1.49900603  3.16531849]
 [ 4.92492485 -6.25042295  4.08944464]]
[[1 2]
 [5 6]
 [3 4]]


In [12]:
#0为初始值，累计三次加1
init = tf.Variable(0)
result = tf.add(init,tf.Variable(1))
update = tf.assign(init,result)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(init))
    for i in range(3):
        sess.run(update)
        print(sess.run(init))

0
1
2
3


In [18]:
#tf.train.Saver
w = tf.Variable([[0.5,1.0]])
x = tf.Variable([[2.0],[1.0]])
y = tf.matmul(w,x)#矩阵乘法

#init all the variable
init = tf.global_variables_initializer()
saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(init)
    
    save_path = saver.save(sess,"//Users//luzhengdong//workplat//test")
    print(save_path)


//Users//luzhengdong//workplat//test


In [19]:
import numpy as np

a = np.zeros((3,3))
b = tf.convert_to_tensor(a)

with tf.Session() as sess:
    print(sess.run(b))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [25]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)

result = tf.multiply(input1,input2)

with tf.Session() as sess:
    print(sess.run([result],feed_dict={input1:[7.],input2:[2.]})) #[result] 加中括号可以打印出dtype，不加直接打印出结果

[array([ 14.], dtype=float32)]


In [26]:
#reduce_mean 举例
import numpy as np
import tensorflow as tf

x = np.array([[1.,2.,3.],[4.,5.,6.]])
sess = tf.Session()

mean1 = sess.run(tf.reduce_mean(x))
mean2 = sess.run(tf.reduce_mean(x, 0))
mean3 = sess.run(tf.reduce_mean(x, 1))

print (mean1)
print (mean2)
print (mean3)

3.5
[ 2.5  3.5  4.5]
[ 2.  5.]


In [ ]:
arr = np.array([[31,23,4,24,27,34],
				[18,3,25,0,6,35],
				[28,14,33,22,20,8],
				[13,30,21,19,7,9],
				[16,1,26,32,2,29],
				[17,12,5,11,10,15]
                
